### ISSUE TITLE
Request: Pls add packet for disabling an alarm

### ISSUE THREAD

**Issue by paaguti** [fbiego/dt78#2]
Hi, 

would you be so kind to include the packet to disable an alarm. Having problems with the App, I finally wrote a simple Python3 script to set the time on my DT78 from Linux. I'd like to be able to control the alarms from it too.

Thx a ton

**Comment by fbiego** [comment]
check this commit; [ecea966](https://github.com/fbiego/dt78/commit/ecea966daa95a935e45b84d8f88d3533a2bea5bb)
