### ISSUE TITLE
Weather support

### ISSUE THREAD

**Issue by Anarbb** [fbiego/dt78#4]
Hey I have an L11 watch model and it has a widget for weather but it doesn't update when I connect it to my phone with DT78 works fine with the official app, is there any plans of adding support to this?

**Comment by fbiego** [comment]
Hello, right now I don't have the command for updating the widget. This is because the DT78 watch does not have weather support.
I'll try to get a watch that supports the weather so I can reverse engineer it.

**Comment by Anarbb** [comment]
i'm not sure what brand mine is, but it shows up as I9 on BT search and the firmware version is 11.01, and uses WearFit2, good luck on the app love seeing projects like these since all the apps from these manufacturers are probably Chinese spyware lmao

**Comment by fbiego** [comment]
hello friend, it seems I picked up the same smartwatch as yours
I have i9 on BT and 11.01 firmware

On the dt78 app it shows as L11 which I will fix
I also noticed it has a custom background feature that is not detected by the app due to the incorrect type.

I hope to fix this as soon as I can

**Comment by Anarbb** [comment]
Hey, That is great news!
hope more people find this project and support it, I personally don't have any experience with this and isn't really my thing but I'll make sure to tip here and there when I can :D keep up

**Comment by fbiego** [comment]
Thanks for your donation @Anarbb, it goes a long way to support the project.  Much appreciated
